# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXSBew-QNhNkMkz2sLp9FRCLGP1qCT69
"""

import pandas as pd

ventas_ancho = {
    'Producto': ['Laptop', 'Mouse'],
    'Enero': [1000, 20],
    'Febrero': [1100, 25]
}
ventas_ancho

ventas_ancho_df = pd.DataFrame(ventas_ancho)
ventas_ancho_df
#

ventas_ancho_df.describe()

ventas_ancho_df.info()
#

ventas_ancho_df.head()

ventas_ancho_df.tail()
#

ventas_ancho_df.columns

ventas_ancho_df.index
#

ventas_ancho_df.drop_duplicates()

ventas_ancho_df.Enero

ventas_ancho_df.keys()

ventas_ancho_df.values
#

"""Transformación: Usa pandas para pasar estos datos a formato "largo" (que la columna 'Mes' sea variable y 'Ventas' sea el valor).  """

ventas_largo_df = ventas_ancho_df.melt(id_vars='Producto', var_name='Mes', value_name='Ventas')
ventas_largo_df

ventas_largo_df.Ventas

"""Limpieza/Cálculo: Aplica un descuento del 10% a todos los valores de ventas usando Dictionary Comprehension sobre los valores numéricos."""

ventas_largo_df.Ventas = ventas_largo_df.Ventas.apply(lambda x: x * 0.9)
ventas_largo_df
#

ventas_largo_df.Ventas